Sync with upstream orchid

diff --git a/lib/requiem b/lib/requiem
--- a/lib/requiem
+++ b/lib/requiem
@@ -1,8 +1,6 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-# LIB REQUIEM CENTOS VERSION
-
-function check_os {
+check_os() {
     if type lsb_release >/dev/null 2>&1 ; then
         distro=$(lsb_release -i -s)
     elif [ -e /etc/os-release ] ; then
@@ -22,7 +20,19 @@ function check_os {
     esac
 }
 
-function requirement {
+apt_requirement() {
+    # Use dpkg-query present in all debian based to check for dependencies.
+    if [[ $(/usr/bin/dpkg-query --show --showformat='${db:Status-Status}\n' "$1") = "installed" ]]; then
+	    echo -e "[\e[92m✔\e[39m]::[$1]: is installed!";
+    else
+        echo -e "[\e[1m\e[91mx\e[39m]::[ERROR]: This Breed requires $1!";
+        echo -e "You can install [\e[1m\e[91m$1\e[39m] using the following order as superuser:";
+        echo "apt install $1"
+        exit 1
+    fi
+}
+
+requirement() {
     command -v "$1" > /dev/null 2>&1
 	if [ "$?" -eq "0" ]; then
 	    echo -e "[\e[92m✔\e[39m]::[$1]: is installed!";
@@ -32,14 +42,14 @@ function requirement {
     fi
 }
 
-function check_root {
+check_root() {
     if [ "$(id -u)" != "0" ]; then
         echo "This script must be run as root" 1>&2
         exit 1
     fi
 }
 
-function validate_ip() {
+validate_ip() {
     local ip=$1
     local stat=1
 
